export const ActionTypes = () => {
  const SET_PRODUCTS = "SET_PRODUCTS";
  const SELECTED_PRODUCT = "SELECTED_PRODUCTS";
  const REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT";
};

/*export const ActionTypes = () => {
  SET_PRODUCTS: "SET_PRODUCTS";
  SELECTED_PRODUCT: "SELECTED_PRODUCTS";
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT";
};*/

/*export const SET_PRODUCTS = "SET_PRODUCTS";
export const SELECTED_PRODUCT = "SELECTED_PRODUCTS";
export const REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT";*/
